"""Generate the browser-safe field catalog from the canonical YAML file."""

from __future__ import annotations

import json
from pathlib import Path

from app.data_dictionary import FIELDS


TARGET = Path(__file__).parents[2] / "frontend" / "src" / "generated" / "fields.ts"


def main():
    payload = json.dumps(FIELDS.as_frontend_payload(), indent=2, sort_keys=True)
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(
        "// Generated by backend/scripts/generate_frontend_fields.py. Do not edit.\n"
        f"export const fields = {payload} as const;\n\n"
        "export type FieldName = keyof typeof fields;\n"
        "export const fieldLabel = (name: string) => "
        "fields[name as FieldName]?.label ?? name;\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
